### ISSUE TITLE
Question about test file

### ISSUE THREAD

**Issue by chiachia36** [iml130/mlir-emitc#273]
Hi,
There are Mobilenetv2 files in MLIR, but these files are not manual.
I wonder that where could I find the original files to generate these MLIR files.
Thanks!

**Comment by marbre** [comment]
You find those files in our [scripts](https://github.com/iml130/mlir-emitc/tree/main/scripts) directory. It depends if you are interested to translate a model to TOSA or to MHLO, but the file you are looking for are `e2e_test.sh` (for MHLO) and `e2e_test_tosa.sh` (for TOSA). The bash script should give you an quite good idea of how to combine most of the Python scripts we provide. In addition, you can use the [`get_mobilenet_v2.py`](https://github.com/iml130/mlir-emitc/blob/main/scripts/get_mobilenet_v2.py) script to grab MobileNetV2 (which can then be passed to one of our e2e scripts).
