### ISSUE TITLE
Invalid Pass Pipeline

### ISSUE THREAD

**Issue by chiachia36** [iml130/mlir-emitc#276]
Hi,
Thanks for reply of last issue.
I tried to use [e2e_test.sh ](https://github.com/iml130/mlir-emitc/blob/main/scripts/e2e_test.sh) to generate model in EmitC dialect.
Here is my command.
`./e2e_test_tosa.sh saved_model/my_model/ ../reference-implementation/include/ ../build/bin/ clang 32 0 /workspace/mlir-emitc/scripts/test_e2e/ `

Here is the error message I got.
```
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_mlir.py", line 84, in experimental_run_pass_pipeline
    mlir_txt.encode('utf-8'), pass_pipeline.encode('utf-8'), show_debug_info)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid pass_pipeline: MLIR Textual PassPipeline Parser:1:105: error: 'tf-device-decompose-resource-ops' does not refer to a registered pass or pass pipeline
symbol-dce,tf-standard-pipeline,builtin.func(tf-device-index-selector),inline,canonicalize,builtin.func(tf-device-decompose-resource-ops),builtin.func(tf-functional-control-flow-to-cfg),inline,symbol-dce,canonicalize,tf-saved-model-optimize-global-tensors,tf-saved-model-freeze-global-tensors
```

Did I misunderstand anything?

I also tried to use savedmodel_to_tf_dialect.py and tf_to_tosa_dialect.py to achieve the goal.
When I ran tf_to_tosa_dialect.py, I got the similar error message.
```
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_mlir.py", line 84, in experimental_run_pass_pipeline
    mlir_txt.encode('utf-8'), pass_pipeline.encode('utf-8'), show_debug_info)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid pass_pipeline: MLIR Textual PassPipeline Parser:1:100: error: 'tosa-fuse-bias-tf' does not refer to a registered pass or pass pipeline
inline,canonicalize,cse,builtin.func(affine-loop-fusion),builtin.func(affine-scalrep),builtin.func(tosa-fuse-bias-tf),builtin.func(tosa-legalize-tf),builtin.func(tosa-infer-shapes),builtin.func(tosa-make-broadcastable),inline,symbol-dce
```

Thanks for helping a lot!

**Comment by marbre** [comment]
Please make sure that you are using the TensorFlow version specified in our [requirements.txt](https://github.com/iml130/mlir-emitc/blob/main/scripts/requirements.txt) file. Those passes were registered in a later version of TensorFlow, older version only support those passes via the `tf-opt` command line tool but not via the Python API. Please re-open if the issue still persists.
