### ISSUE TITLE
Variadic MHLO reduce support

### ISSUE THREAD

**Issue by jpienaar** [iml130/mlir-emitc#277]
Currently the converter doesn't support MHLO reduce with variadic reduce, so computations like

```mlir
%752:2 = mhlo.reduce(%748 init: %750), (%749 init: %751) across dimensions = [1] : (tensor<1x2xf32>, tensor<1x2xi32>, tensor<f32>, tensor<i32>) -> (tensor<1xf32>, tensor<1xi32>)
     reducer(%arg35: tensor<f32>, %arg37: tensor<f32>) (%arg36: tensor<i32>, %arg38: tensor<i32>)  {
      %764 = "mhlo.compare"(%arg35, %arg37) {comparison_direction = "GE"} : (tensor<f32>, tensor<f32>) -> tensor<i1>
      %765 = "mhlo.select"(%764, %arg35, %arg37) : (tensor<i1>, tensor<f32>, tensor<f32>) -> tensor<f32>
      %766 = "mhlo.compare"(%arg35, %arg37) {comparison_direction = "EQ"} : (tensor<f32>, tensor<f32>) -> tensor<i1>
      %767 = mhlo.minimum %arg36, %arg38 : tensor<i32>
      %768 = "mhlo.select"(%764, %arg36, %arg38) : (tensor<i1>, tensor<i32>, tensor<i32>) -> tensor<i32>
      %769 = "mhlo.select"(%766, %767, %768) : (tensor<i1>, tensor<i32>, tensor<i32>) -> tensor<i32>
      "mhlo.return"(%765, %769) : (tensor<f32>, tensor<i32>) -> ()
    }
```

doesn't convert.

**Comment by marbre** [comment]
I assume we are talking about multiple returns? This is indeed not possible, see https://github.com/iml130/mlir-emitc/blob/cbbeed65364e9e1b62737fec18e08587e3945bee/lib/Dialect/EmitC/Conversion/MHLORegionOpsToEmitC.cpp#L153%C3%9FL157 and reported in our [MHLO HLO Op Coverage](https://github.com/iml130/mlir-emitc/blob/main/docs/mhlo-op-coverage.md) docs. Is this a requirement for the work on your side?

**Comment by jpienaar** [comment]
Indeed else for example argmax lowering to MHLO doesn't work which rules out a large class of models.

**Comment by simon-camp** [comment]
I've briefly looked into this. It should be fairly easy to support the two results case via an overload, but I don't see an easy way to generalize the [reduction function](https://github.com/iml130/mlir-emitc/blob/cbbeed65364e9e1b62737fec18e08587e3945bee/reference-implementation/include/emitc/mhlo.h#L468) to arbitrary arity.

**Comment by jpienaar** [comment]
Two result case would go a long way (I think it is probably second most common post plain single result). That would be very helpful.

For the arbitrary arity case, could it be expanded to a for loop constantly reapplying function? (for (...) { x = f(val[it], x) } kind). So you'd need a function to be able to get the slice of the tensor at iteration I kind.

**Comment by marbre** [comment]
The two result case is now supported with #285 landed.
