### ISSUE TITLE
Composing legalizations

### ISSUE THREAD

**Issue by jpienaar** [iml130/mlir-emitc#278]
It appears as if the legalization passes can't be composed to handle an input file consisting of TOSA and MHLO ops to EmitC.

**Comment by jpienaar** [comment]
This would allow using the argmax from TOSA with a primarily MHLO model.

Is it a requirement that the lowering to EmitC be a one-shot?

**Comment by marbre** [comment]
> This is indeed not possible with the passes we have right now. Is this relevant for the work on your side?

I must correct my statement. The conversion passes are implemented as partial conversions and it is indeed possible to pass mixed input files. For example

```mlir
func @mixed_dialects(%arg0: tensor<2xi32>) -> i32 {
  %0 = "mhlo.constant"() {value = dense<1> : tensor<2xi32>} : () -> tensor<2xi32>
  %1 = "tosa.const"() {value = dense<[3, 0, 1, 2]> : tensor<4xi32>} : () -> tensor<4xi32>
  %2 = emitc.call "func_a" (%0, %1) : (tensor<2xi32>, tensor<4xi32>) -> i32
  return %2 : i32
}
```
can be converted by passing `--convert-tosa-to-emitc --convert-mhlo-to-emit` to `emitc-opt` to
```mlir
func @mixed_dialects(%arg0: tensor<2xi32>) -> i32 {
  %0 = "emitc.constant"() {value = dense<1> : tensor<2xi32>} : () -> tensor<2xi32>
  %1 = "emitc.constant"() {value = dense<[3, 0, 1, 2]> : tensor<4xi32>} : () -> tensor<4xi32>
  %2 = emitc.call "func_a"(%0, %1) : (tensor<2xi32>, tensor<4xi32>) -> i32
  return %2 : i32
}
```
Using `emitc-translate` or `mlir-translate` (from MLIR upstream) this can be translated to

```C++
int32_t mixed_dialects(Tensor<int32_t, 2> v1) {
  Tensor<int32_t, 2> v2 = {1, 1};
  Tensor<int32_t, 4> v3 = {3, 0, 1, 2};
  int32_t v4 = func_a(v2, v3);
  return v4;
}
```

**Comment by marbre** [comment]
> This would allow using the argmax from TOSA with a primarily MHLO model.

The problem you were facing is that there is no conversion for `tosa.argmax`. I've created #279 to track this. Please re-open or fill a new issue if I got things wrong.

**Comment by jpienaar** [comment]
Ah I hadn't checked argmax support there. Thanks!
