### ISSUE TITLE
MHLO select scalar pred support

### ISSUE THREAD

**Issue by jpienaar** [iml130/mlir-emitc#280]
select allows for scalar predicate support while reference implementation does not.

**Comment by marbre** [comment]
I am not sure if https://www.tensorflow.org/mlir/hlo_ops#mhloselect_mlirmhloselectop was already available when we implemented the reference implementation. Indeed, `pred` should be a "tensor of pred (AKA boolean or 1-bit integer) values", but "[..] may also be a scalar in which case it is broadcasted". A testcase can be can be found in the mlir-hlo repo: https://github.com/tensorflow/mlir-hlo/blob/57288f12595a2ee0488806672a42da59b1e56e13/tests/Dialect/mhlo/ops.mlir#L954-L958
