### ISSUE TITLE
Plan to handle quantization for tosa-to-emitc?

### ISSUE THREAD

**Issue by j2kun** [iml130/mlir-emitc#350]
Hi there,

I noticed there is no support for quantization in the tosa dialect. I'm wondering if that's on the roadmap at all.

**Comment by marbre** [comment]
Hi @j2kun,

We discussed this internally some time ago and are aware of what steps would need to be taken. However, we haven't worked on this during the last months and don't have this on our roadmap so far. I've also talked to @jpienaar about this.

Nevertheless, we are happy to work/collaborate on this if there is the demand.

**Comment by marbre** [comment]
So it is okay if I close this for now? As mentioned, we are happy to work on this if there is a deeper interest and we are also open for collaboration.
