### ISSUE TITLE
hi,where I can find InsertEmitCTosaIncludeBase definition? thx!

### ISSUE THREAD

**Issue by AIYoungcino** [iml130/mlir-emitc#381]
https://github.com/iml130/mlir-emitc/blob/cde9e9664106555955b97e48ed1cf137d0e1116a/lib/Dialect/EmitC/Transforms/InsertIncludes.cpp#L59

**Comment by marbre** [comment]
Hi @AIYoungcino,
The class `InsertEmitCTosaIncludeBase` is auto-generated via TableGen. You'll find the definition in the auto-generated file `include/emitc/Dialect/EmitC/Transforms/Passes.h.inc` in your build folder. Hope this helps.
