### ISSUE TITLE
Use rewriter instead of utility functions for attribute conversion

### ISSUE THREAD

**Issue by simon-camp** [iml130/mlir-emitc#402]
Replace all uses of `i64ElementsAttr(int64_t, size_t, MLIRContext*)` and `getI64ElementsAttr(const ArrayRef<long>, MLIRContext *)` with `rewriter.getDenseI64ArrayAttr(ArrayRef<int64_t>)`.

**Comment by marbre** [comment]
I already have the patch ready ;)

**Comment by marbre** [comment]
> Replace all uses of `i64ElementsAttr(int64_t, size_t, MLIRContext*)` and `getI64ElementsAttr(const ArrayRef<long>, MLIRContext *)` with `rewriter.getDenseI64ArrayAttr(ArrayRef<int64_t>)`.

Well essentially we can replace `getI64ElementsAttr` with `rewriter.getI64TensorAttr`. `getDenseI64ArrayAttr` you get an `DenseI64ArrayAttr` which cannot be emitted by the CppEmitter.
